### PR TITLE
WIP: Server projects

### PR DESCRIPTION
**Pull request by SebastianStehle**
No tests yet. But a way to provide comments.

### CODE REVIEW

**Comment by LSViana** [comment]
Hi, @SebastianStehle!

I see that this PR is still a WIP and I won't have time today and over the weekend to check it yet, then I'll try to check it early next week.

Just letting you know that I'm aware of your efforts here and I appreciate your help! 🙌

**Comment by SebastianStehle** [comment]
Yes, the PR is a little bit chaotic, therefore it is WIP, but I think it is ready to get merged, because the full project is WIP. if you are interested we can also schedule a call and we can discuss things.

**Comment by LSViana** [comment]
Hi, @SebastianStehle!

Sure, I'll check your schedule for next week and I may schedule a call if I have some time available as well.

I'll have to check through your code changes first because, despite the project being a WIP, every detail of the PR needs to be reviewed to avoid accidental changes like the empty `Class1.cs` file at the `YDotNet.Native` namespace, for example.

Additionally, all the code added to the project so far was accompanied by tests and keeps the standard of other Yrs bindings. I see the amount of changes here is huge and we can't guarantee everything is working right now. I'd like to keep the project growth manageable.

The most likely path forward will be to integrate your changes in batches as we can discuss them. I'll also need to check how to organize the repository from the point of view of publishing the NuGet packages later.

**Comment by SebastianStehle** [comment]
Yes, everything that has happened today has nothing to do with the server project and can be removed. Tests are also on the todo list but I was focusing on manual tests first because I had to change the design so often that refactoring the tests would have been a nightmare.

**Comment by SebastianStehle** [comment]
Closing in favor of https://github.com/LSViana/ydotnet/pull/44. The other PR focuses on binaries and the fixes to get it running under all operation systems. When this is done I am going to reopen another PR for the server part.

**Pull request closed without merging**
